<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <title>Exceptions in v8 - fork()
    </title>
    <link rel="alternate" href="http://ripsawridge.github.io//feed.xml" type="application/rss+xml" title="Notes from my endeavors">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic|Anonymous+Pro:400,700,400italic,700italic|Merriweather:400,700,300">
    <link rel="stylesheet" href="/css/main.css">
  </head>
  <body class="article-detail">
    <header class="header">
      <div class="content-wrap">
        <h1>Exceptions in v8</h1>
        <p class="author">Written by <span class="author"><a href="mailto:ripsawridge@gmail.com">Michael Stanton</a></span>
        </p>
      </div>
    </header>
    <div id="content">
      <div class="content-wrap">
        <article class="article">
          <section class="content"><p>How do exceptions work in v8? Let’s see.
<img src="images/peppermint.jpg" width=200 align="right"></p>
<p>I’ll use a little program to motivate our<span class="widont">&nbsp;</span>discussion:</p>
<pre><code class="language-javascript"><span class="function"><span class="keyword">function</span> <span class="title">foo</span>(<span class="params">a</span>) </span>{
  <span class="keyword">if</span> (a === <span class="literal">true</span>) <span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">"Oh no."</span>);
}

<span class="function"><span class="keyword">function</span> <span class="title">bar</span>(<span class="params">a</span>) </span>{
  <span class="keyword">try</span> {
    foo(a);
  } <span class="keyword">catch</span>(e) {
    print(e);
  }
}

bar(<span class="literal">true</span>);</code></pre>
<p>The bytecode for <code>foo</code> looks like this (I cleaned up the output from <code>--print-bytecode</code> slightly):</p>
<pre><code>Generated bytecode for function: foo
Parameter count 2
Register count 2
Frame size 8
0            StackCheck
1            LdaTrue
2            TestEqualStrict a0, [0]
5            JumpIfFalse [19] (@ 24)
7            LdaGlobal [0], [1]
10           Star r0
12           LdaConstant [1]
14           Star r1
16           Ldar r0
18           Construct r0, r1-r1, [3]
23           Throw
24           LdaUndefined
25           Return
Constant pool (size = 2)
       0: &lt;String[#5]: Error&gt;
       1: &lt;String[#6]: Oh no.&gt;
Handler Table (size = 0)</code></pre><p>The important thing here is that if the <code>JumpIfFalse</code> isn’t taken, then we create an Error object, leaving it in the accumulator
for the <code>Throw</code> bytecode. We don’t expect to ever return from that bytecode.
How strange and<span class="widont">&nbsp;</span>interesting…</p>
<p>We’ll get right into that, but first let me show you the bytecode for <code>bar</code> as
well, because it has a catch handler that’ll be a point of interest for<span class="widont">&nbsp;</span>us:</p>
<pre><code>Generated bytecode for function: bar
Parameter count 2
Register count 4
Frame size 16
0            StackCheck
1            Mov &lt;context&gt;, r0
4            LdaGlobal [0], [0]
7            Star r1
9            CallUndefinedReceiver1 r1, a0, [2]
13           Jump [30] (@ 43)
15           Star r1
17           CreateCatchContext r1, [1]
20           Star r0
22           LdaTheHole
23           SetPendingMessage
24           Ldar r0
26           PushContext r1
28           LdaGlobal [2], [4]
31           Star r2
33           LdaImmutableCurrentContextSlot [2]
35           Star r3
37           CallUndefinedReceiver1 r2, r3, [6]
41           PopContext r1
43           LdaUndefined
44           Return
Constant pool (size = 3)
       0: &lt;String[#3]: foo&gt;
       1: &lt;ScopeInfo CATCH_SCOPE [5]&gt;
       2: &lt;String[#5]: print&gt;
Handler Table (size = 16)
  from   to       hdlr (prediction,   data)
 (   4,  13)  -&gt;    15 (prediction=1, data=0)</code></pre><p>Here you can see the call to <code>foo</code> at offset 9, then a jump down to offset 43
where we return undefined (how boring). Offsets 15 to 41 are the catch handler.
The <code>Handler Table</code> at the bottom lays this out. It shows the try region goes
from offsets 4 to 13, and the handler that corresponds to it starts at offset<span class="widont">&nbsp;</span>15.</p>
<p>Very nice.</p>
<p>So what does the <code>Throw</code> bytecode do? Like all bytecodes, the implementation
is provided in file <a href="https://cs.chromium.org/chromium/src/v8/src/interpreter/interpreter-generator.cc">interpreter-generator.cc</a>:</p>
<pre><code class="language-cpp"><span class="comment">// Throws the exception in the accumulator.</span>
IGNITION_HANDLER(Throw, InterpreterAssembler) {
  TNode&lt;Object&gt; exception = GetAccumulator();
  TNode&lt;Context&gt; context = GetContext();
  CallRuntime(Runtime::kThrow, context, exception);
  <span class="comment">// We shouldn't ever return from a throw.</span>
  Abort(AbortReason::kUnexpectedReturnFromThrow);
  Unreachable();
}</code></pre>
<p>Okay, that’s easy, we just call a runtime function. It’s nice to see the abort
in here that documents our expectations. The runtime function (in 
<a href="https://cs.chromium.org/chromium/src/v8/src/runtime/runtime-internal.cc">runtime-internal.cc</a>) is also simple, just returning the result of Isolate::Throw() back from C++
to the world of generated<span class="widont">&nbsp;</span>code:</p>
<pre><code class="language-cpp">RUNTIME_FUNCTION(Runtime_Throw) {
  <span class="function">HandleScope <span class="title">scope</span><span class="params">(isolate)</span></span>;
  DCHECK_EQ(<span class="number">1</span>, args.length());
  <span class="keyword">return</span> isolate-&gt;Throw(args[<span class="number">0</span>]);
}</code></pre>
<p>You’d <em>never suspect</em> that we just skipped over something absolutely breathtaking,
but we did. Let’s return to it after a look at the end of the road, <code>Isolate::Throw</code>:</p>
<pre><code class="language-cpp">
Object Isolate::Throw(Object raw_exception, MessageLocation* location) {
  DCHECK(!has_pending_exception());

  <span class="function">HandleScope <span class="title">scope</span><span class="params">(<span class="keyword">this</span>)</span></span>;
  Handle&lt;Object&gt; exception(raw_exception, <span class="keyword">this</span>);

  ...
  ... skipping over some interesting stuff to focus on the <span class="string">"bones"</span> of
  ... the function.
  ...

  <span class="comment">// Set the exception being thrown.</span>
  set_pending_exception(*exception);
  <span class="keyword">return</span> ReadOnlyRoots(heap()).exception();
}</code></pre>
<p>The main thing that happens here is that we save the exception object in
the isolate, and return a curious sentinel value in the global root set,
<code>exception()</code>. We only indicate that there is an exception pending in the
system by saving this value, and don’t do anything exotic. The crazy stuff
is yet to come, awakened into hideous life by that innocuous sentinel<span class="widont">&nbsp;</span>value.</p>
<p>Here’s what happens now. When the runtime function returns this value to
generated code, it comes into some tricky platform dependent code we call
<code>CEntryStub</code>. This code is responsible for building a frame and calling
into C++. It also recognizes pending exceptions and (gasp!) drops frames
from the stack in order to call the topmost handler. Let’s have a look, now in
<a href="https://cs.chromium.org/chromium/src/v8/src/builtins/ia32/builtins-ia32.cc">builtins-ia32.cc</a>,
method <code>Builtins::Generate_CEntry</code>:</p>
<pre><code class="language-cpp">  ...
  __ call(kRuntimeCallFunctionRegister);

  <span class="comment">// Result is in eax or edx:eax - do not destroy these registers!</span>

  <span class="comment">// Check result for exception sentinel.</span>
  Label exception_returned;
  __ CompareRoot(eax, RootIndex::kException);
  __ j(equal, &amp;exception_returned);
  ...
  <span class="comment">// Exit the JavaScript to C++ exit frame.</span>
  __ LeaveExitFrame(save_doubles == kSaveFPRegs, argv_mode == kArgvOnStack);
  __ ret(<span class="number">0</span>);
  ...

  <span class="comment">// Handling of exception.</span>
  __ bind(&amp;exception_returned);</code></pre>
<p>The code above is dutifully calling the runtime function requested. In our
case, it was <code>Runtime_Throw</code>, but this body of code is used for the many
dozens of runtime functions we have. After the call, you can see we are
comparing the return value with that magic <code>exception</code> sentinel (here it
has a different name, <code>RootIndex::kException</code>. We’ve often got a few ways
to refer to something, depending on what kind of code you’re in. All part
of the fun…). If we don’t see it, we can return to the bytecode handler,
builtin or stub, getting somewhat closer to user code. Otherwise, we do
interesting<span class="widont">&nbsp;</span>things:</p>
<pre><code class="language-cpp">  <span class="comment">// Ask the runtime for help to determine the handler. This will set eax to</span>
  <span class="comment">// contain the current pending exception, don't clobber it.</span>
  ExternalReference find_handler =
      ExternalReference::Create(Runtime::kUnwindAndFindExceptionHandler);
  {
    <span class="function">FrameScope <span class="title">scope</span><span class="params">(masm, StackFrame::<span class="caps">MANUAL</span>)</span></span>;
    __ PrepareCallCFunction(<span class="number">3</span>, eax);
    __ mov(Operand(esp, <span class="number">0</span> * kSystemPointerSize), Immediate(<span class="number">0</span>));  <span class="comment">// argc.</span>
    __ mov(Operand(esp, <span class="number">1</span> * kSystemPointerSize), Immediate(<span class="number">0</span>));  <span class="comment">// argv.</span>
    __ Move(esi,
            Immediate(ExternalReference::isolate_address(masm-&gt;isolate())));
    __ mov(Operand(esp, <span class="number">2</span> * kSystemPointerSize), esi);
    __ CallCFunction(find_handler, <span class="number">3</span>);
  }

  <span class="comment">// Retrieve the handler context, <span class="caps">SP</span> and <span class="caps">FP</span>.</span>
  __ mov(esp, __ ExternalReferenceAsOperand(pending_handler_sp_address, esi));
  __ mov(ebp, __ ExternalReferenceAsOperand(pending_handler_fp_address, esi));
  __ mov(esi,
         __ ExternalReferenceAsOperand(pending_handler_context_address, esi));</code></pre>
<p>First we call back into C++, searching for an exception handler. We’ll
definitely have one. I skipped over a section of code in <code>Isolate::Throw</code> that
would abort execution if there is no handler. I really enjoy what’s next:
we simply set the stack pointer and the frame pointer to the appropriate values
for a handler somewhere below us on the stack. What about dutifully
returning from all the functions we may have between here and<span class="widont">&nbsp;</span>there?</p>
<p>Nope!</p>
<p>A few lines later we begin executing that handler like<span class="widont">&nbsp;</span>this:</p>
<pre><code class="language-cpp">  <span class="comment">// Compute the handler entry address and jump to it.</span>
  __ mov(edi, __ ExternalReferenceAsOperand(pending_handler_entrypoint_address,
                                            edi));
  __ jmp(edi);
}</code></pre>
<p>That final curly brace is just showing that these are the last lines of the
CEntry stub. What a way to go, am I<span class="widont">&nbsp;</span>right?</p>
<p>Now it’s a good time to remember that we have a catch handler. It’s in
function <code>bar()</code>, and it’s address is at offset 15 in the bytecode. So
whatever <code>Runtime_UnwindAndFindExceptionHandler</code> does, it better return
precisely that information to the CEntryStub so that the stack, frame and
instruction pointer can be set<span class="widont">&nbsp;</span>appropriately.</p>
<h2 id="unwinding-and-finding-stuff">Unwinding and finding<span class="widont">&nbsp;</span>stuff</h2>
<p>The entirety of this work is in <a href="https://cs.chromium.org/chromium/src/v8/src/execution/isolate.cc?type=cs&amp;q=Isolate::UnwindAndFindHandler&amp;sq=package:chromium&amp;g=0&amp;l=1623">Isolate::UnwindAndFindHandler</a>:</p>
<pre><code class="language-cpp">Object Isolate::UnwindAndFindHandler() {
  Object exception = pending_exception();
  ...
  <span class="comment">// Special handling of termination exceptions, uncatchable by JavaScript and</span>
  <span class="comment">// Wasm code, we unwind the handlers until the top <span class="caps">ENTRY</span> handler is found.</span>
  <span class="keyword">bool</span> catchable_by_js = is_catchable_by_javascript(exception);
  ...</code></pre>
<p>It begins innocently enough, picking up the pending exception object we saved
earlier in the isolate. We also learn that some exceptions can’t be caught
by javascript. In practice this is only a termination exception. No stopping
that<span class="widont">&nbsp;</span>train…</p>
<p>Now we walk the stack looking for handlers among the different kinds of frames
we might have. I’ll just focus on interpreted and optimized javascript<span class="widont">&nbsp;</span>code:</p>
<pre><code class="language-cpp">  ...
  <span class="comment">// Compute handler and stack unwinding information by performing a full walk</span>
  <span class="comment">// over the stack and dispatching according to the frame type.</span>
  <span class="keyword">for</span> (StackFrameIterator iter(<span class="keyword">this</span>);; iter.Advance()) {
    <span class="comment">// Handler must exist.</span>
    <span class="caps">DCHECK</span>(!iter.done());

    StackFrame* frame = iter.frame();

    <span class="keyword">switch</span> (frame-&gt;type()) {
      <span class="keyword">case</span> StackFrame::<span class="caps">ENTRY</span>:
      <span class="keyword">case</span> StackFrame::CONSTRUCT_ENTRY: ...
      <span class="keyword">case</span> StackFrame::C_WASM_ENTRY: ...
      <span class="keyword">case</span> StackFrame::WASM_COMPILED: ...
      <span class="keyword">case</span> StackFrame::WASM_COMPILE_LAZY: ...
      <span class="keyword">case</span> StackFrame::WASM_INTERPRETER_ENTRY: ...
      <span class="keyword">case</span> StackFrame::<span class="caps">STUB</span>: ...
      <span class="keyword">case</span> StackFrame::<span class="caps">BUILTIN</span>: ...
      <span class="keyword">case</span> StackFrame::JAVA_SCRIPT_BUILTIN_CONTINUATION_WITH_CATCH: ...
      <span class="keyword">case</span> StackFrame::<span class="caps">OPTIMIZED</span>: ...
      <span class="keyword">case</span> StackFrame::<span class="caps">INTERPRETED</span>: ...
      <span class="keyword">default</span>:
        <span class="comment">// All other types can not handle exception.</span>
        <span class="keyword">break</span>;
  }</code></pre>
<p>Here’s what we do for an interpreted frame. As you might suspect, the
verbosity of comments indicates<span class="widont">&nbsp;</span>“hairyness”:</p>
<pre><code class="language-cpp">  <span class="keyword">case</span> StackFrame::<span class="caps">INTERPRETED</span>: {
    <span class="comment">// For interpreted frame we perform a range lookup in the handler table.</span>
    <span class="keyword">if</span> (!catchable_by_js) <span class="keyword">break</span>;
    InterpretedFrame* js_frame = <span class="keyword">static_cast</span>&lt;InterpretedFrame*&gt;(frame);
    <span class="keyword">int</span> register_slots = InterpreterFrameConstants::RegisterStackSlotCount(
        js_frame-&gt;GetBytecodeArray().register_count());
    <span class="keyword">int</span> context_reg = <span class="number">0</span>;  <span class="comment">// Will contain register index holding context.</span>

    <span class="keyword">int</span> offset =
        js_frame-&gt;LookupExceptionHandlerInTable(&amp;context_reg, <span class="literal">nullptr</span>);
    <span class="keyword">if</span> (offset &lt; <span class="number">0</span>) <span class="keyword">break</span>;

    <span class="comment">// Compute the stack pointer from the frame pointer. This ensures that</span>
    <span class="comment">// argument slots on the stack are dropped as returning would.</span>
    <span class="comment">// Note: This is only needed for interpreted frames that have been</span>
    <span class="comment">//       materialized by the deoptimizer. If there is a handler frame</span>
    <span class="comment">//       in between then {frame-&gt;sp()} would already be correct.</span>
    Address return_sp = frame-&gt;fp() -
                        InterpreterFrameConstants::kFixedFrameSizeFromFp -
                        register_slots * kSystemPointerSize;

    <span class="comment">// Patch the bytecode offset in the interpreted frame to reflect the</span>
    <span class="comment">// position of the exception handler. The special builtin below will</span>
    <span class="comment">// take care of continuing to dispatch at that position. Also restore</span>
    <span class="comment">// the correct context for the handler from the interpreter register.</span>
    Context context =
        Context::cast(js_frame-&gt;ReadInterpreterRegister(context_reg));
    js_frame-&gt;PatchBytecodeOffset(<span class="keyword">static_cast</span>&lt;<span class="keyword">int</span>&gt;(offset));

    Code code =
        builtins()-&gt;builtin(Builtins::kInterpreterEnterBytecodeDispatch);
    <span class="keyword">return</span> FoundHandler(context, code.InstructionStart(), <span class="number">0</span>,
                        code.constant_pool(), return_sp, frame-&gt;fp());
  }</code></pre>
<p>What first popped out of the code for me was the call to the frame to
lookup the exception handler in the table. That’s where our offset 15
should appear as we search for a handler. The next interesting thing
is the line <code>js_frame-&gt;PatchBytecodeOffset(offset)</code>. Since we are
dealing with bytecode we don’t have a <em>machine instruction</em> where
our handler starts. Instead, we’ll be running the interpreter, which
gets the offset from the<span class="widont">&nbsp;</span>frame.</p>
<p>The <code>FoundHandler</code> call is a helper executed on our way out, which sets
those all important return values somewhere that the CEntryStub can
pick them up. Here it<span class="widont">&nbsp;</span>is:</p>
<pre><code class="language-cpp">  <span class="keyword">auto</span> FoundHandler = [&amp;](Context context, Address instruction_start,
                          <span class="keyword">intptr_t</span> handler_offset,
                          Address constant_pool_address, Address handler_sp,
                          Address handler_fp) {
    <span class="comment">// Store information to be consumed by the CEntry.</span>
    thread_local_top()-&gt;pending_handler_context_ = context;
    thread_local_top()-&gt;pending_handler_entrypoint_ =
        instruction_start + handler_offset;
    thread_local_top()-&gt;pending_handler_constant_pool_ = constant_pool_address;
    thread_local_top()-&gt;pending_handler_fp_ = handler_fp;
    thread_local_top()-&gt;pending_handler_sp_ = handler_sp;

    <span class="comment">// Return and clear pending exception. The contract is that:</span>
    <span class="comment">// (1) the pending exception is stored in one place (no duplication), and</span>
    <span class="comment">// (2) within generated-code land, that one place is the return register.</span>
    <span class="comment">// If/when we unwind back into C++ (returning to the JSEntry stub,</span>
    <span class="comment">// or to Execution::CallWasm), the returned exception will be sent</span>
    <span class="comment">// back to isolate-&gt;set_pending_exception(...).</span>
    clear_pending_exception();
    <span class="keyword">return</span> exception;
  };</code></pre>
<p>You can also see that the exception is no longer pending. It is real now,
on it’s way, speeding like a bullet to the chosen<span class="widont">&nbsp;</span>handler.</p>
<p>Let’s have a quick look at how we deal with handlers in optimized<span class="widont">&nbsp;</span>code:</p>
<pre><code class="language-cpp">  <span class="keyword">case</span> StackFrame::<span class="caps">OPTIMIZED</span>: {
    <span class="comment">// For optimized frames we perform a lookup in the handler table.</span>
    <span class="keyword">if</span> (!catchable_by_js) <span class="keyword">break</span>;
    OptimizedFrame* js_frame = <span class="keyword">static_cast</span>&lt;OptimizedFrame*&gt;(frame);
    Code code = frame-&gt;LookupCode();

    <span class="keyword">int</span> offset = js_frame-&gt;LookupExceptionHandlerInTable(<span class="literal">nullptr</span>, <span class="literal">nullptr</span>);
    <span class="keyword">if</span> (offset &lt; <span class="number">0</span>) <span class="keyword">break</span>;

    <span class="comment">// Compute the stack pointer from the frame pointer. This ensures</span>
    <span class="comment">// that argument slots on the stack are dropped as returning would.</span>
    Address return_sp = frame-&gt;fp() +
                        StandardFrameConstants::kFixedFrameSizeAboveFp -
                        code.stack_slots() * kSystemPointerSize;

    ...

    <span class="keyword">return</span> FoundHandler(Context(), code.InstructionStart(), offset,
                        code.constant_pool(), return_sp, frame-&gt;fp());
  }</code></pre>
<p>The table used by the frame is the same “in spirit” as the table for an
interpreted version of the function, only it’s offsets are in machine
instructions.<span class="widont">&nbsp;</span>Cool.</p>
<p>I made sure function <code>bar</code> got optimized, then had a look at the code.
It’s handler table looks like<span class="widont">&nbsp;</span>this:</p>
<pre><code>Handler Table (size = 1)
  offset   handler
      84  -&gt;    ae</code></pre><p>Let’s see if that makes sense to us.<span class="widont">&nbsp;</span>Hmm:</p>
<pre><code>0x36f8277c    7c  mov ecx,[edi+0x17]
0x36f8277f    7f  add ecx,0x3f
0x36f82782    82  call ecx
0x36f82784    84  mov eax,0x5ae80279 ;; object: &lt;undefined&gt;
0x36f82789    89  mov esp,ebp
0x36f8278b    8b  pop ebp
0x36f8278c    8c  ret 0x8

0x36f8278f    8f  mov eax,0xb8
0x36f82794    94  push eax
0x36f82796    96  mov eax,0x1
0x36f8279b    9b  mov edx,0xf7071690 ;; Runtime::StackGuardWithGap
0x36f827a0    a0  mov esi,0x2d8c0c61 ;; object: &lt;NativeContext[261]&gt;
0x36f827a5    a5  mov ecx,eax
0x36f827a7    a7  call 0xf580b760  (CEntry)
0x36f827ac    ac  jmp 0x36f8274a  &lt;+0x4a&gt;

0x36f827ae    ae  mov ecx,0x5ae802f5 ;; object: &lt;the_hole&gt;
0x36f827b3    b3  mov [ebx+0x18d8],ecx
0x36f827b9    b9  mov edi,0x2a9c0c21 ;; object: &lt;JSGlobal Object&gt;
0x36f827be    be  push edi
0x36f827c0    c0  push eax
0x36f827c2    c2  mov [ebp-0x10],eax
0x36f827c5    c5  mov edx,0x566ed920 ;; external reference (&lt;unknown&gt;)
0x36f827ca    ca  mov esi,0x2d8c0c61 ;; object: &lt;NativeContext[261]&gt;
0x36f827cf    cf  mov ecx,0x1
0x36f827d4    d4  mov eax,0x5ae80279 ;; object: &lt;undefined&gt;
0x36f827d9    d9  call 0xf50af0a0  (CallApiCallback)
0x36f827de    de  jmp 0x36f82784  &lt;+0x84&gt;</code></pre><p>Okay, offset 84 is actually right after the call to <code>foo</code>. I’d feel
like I knew what was going on if the offset started at 82, but on the other
hand, the truth is that nothing can throw in here. Conceptually we are at
offset 84 now, as we are inside the call to <code>foo</code>,
so I guess the lookup of the handler should<span class="widont">&nbsp;</span>succeed.</p>
<p>If an exception doesn’t happen, we’ll tear down the frame and exit the
function at offset 8c. Offsets 8f to ac are unrelated to us, they are
dealing with the stack guard and can be ignored (though Jakob Gruber is
doing interesting work right now to repair holes in our stack guard logic,
which protects against unexpected stack overflow during optimized function<span class="widont">&nbsp;</span>deoptimization!).</p>
<p>Offset ae does appear to be our catch handler, though it’s a bit disguised.
It’s making an api call, after which it joins the normal exit of the function.
The api call must be my <code>print(e);</code>. Neat!</p>
<p>There is more to say. For one thing, what is a <em>scheduled</em> exception?
It has to do with <span class="caps">API</span> boundaries. More next time, thanks for joining<span class="widont">&nbsp;</span>me!</p>
</section>
        </article>
      </div>
    </div>
    <footer>
      <div class="content-wrap">
        <div class="nav"><a href="/">&laquo; Full blog</a></div>
        <section class="about"><p>The views expressed here are simply my own and not my employers or anything
wierd.</p>
<p>Also, I am often mistaken and in the process of bumbling about in order
to learn things.</p>
<p><a href="https://app.wercker.com/project/bykey/f7ee9d19a46e8c2f8440b6af414a2acf"><img src="https://app.wercker.com/status/f7ee9d19a46e8c2f8440b6af414a2acf/m/master" alt="wercker status" title="wercker status"></a></p>

        </section>
        <section class="copy">
          <p>&copy; 2019 Michael Stanton &mdash; powered by&nbsp;<a href="https://github.com/jnordberg/wintersmith">Wintersmith</a></p>
        </section>
      </div>
    </footer>
  </body>
</html>